### ISSUE TITLE
Error creating a new project

### ISSUE THREAD

**Issue by ugoano** [googlearchive/code-editor-app#5] opened 2013-06-11 12:33 UTC
Reproduce by creating a new project, giving it a name, and clicking create does not do anything.

In the logs, the error message suggests that `this.prefsFile` is undefined.

On a side note, there are warnings that the project is using deprecated apis.  Hope this helps, I've needed this for a _long_ time

**Comment by SmokyBob** [comment] 2013-06-11 12:45
Please try to see if the info in the Item 3 helps
https://github.com/GoogleChrome/code-editor-app/issues/3

I'm not 100% sure but seems like the error I had

**Comment by ugoano** [comment] 2013-06-11 12:53
Thanks @SmokyBob , looks like I won't be able to run it without the latest dev build - not ready to make the switch yet :-) Thanks!

**Comment by dinhvh** [comment] 2013-06-25 22:52
Closing as duplicate of #3.

**Closed as completed by dinhvh** 2013-06-25 22:52 UTC
